(function($) {
    $(document).ready(function() {
	
	$('#RandWalk').scianimator({
	    'images': ['images/RandWalk1.png', 'images/RandWalk2.png', 'images/RandWalk3.png', 'images/RandWalk4.png', 'images/RandWalk5.png', 'images/RandWalk6.png', 'images/RandWalk7.png', 'images/RandWalk8.png', 'images/RandWalk9.png', 'images/RandWalk10.png', 'images/RandWalk11.png', 'images/RandWalk12.png', 'images/RandWalk13.png', 'images/RandWalk14.png', 'images/RandWalk15.png', 'images/RandWalk16.png', 'images/RandWalk17.png', 'images/RandWalk18.png', 'images/RandWalk19.png', 'images/RandWalk20.png', 'images/RandWalk21.png', 'images/RandWalk22.png', 'images/RandWalk23.png', 'images/RandWalk24.png', 'images/RandWalk25.png', 'images/RandWalk26.png', 'images/RandWalk27.png', 'images/RandWalk28.png', 'images/RandWalk29.png', 'images/RandWalk30.png', 'images/RandWalk31.png', 'images/RandWalk32.png', 'images/RandWalk33.png', 'images/RandWalk34.png', 'images/RandWalk35.png', 'images/RandWalk36.png', 'images/RandWalk37.png', 'images/RandWalk38.png', 'images/RandWalk39.png', 'images/RandWalk40.png', 'images/RandWalk41.png', 'images/RandWalk42.png', 'images/RandWalk43.png', 'images/RandWalk44.png', 'images/RandWalk45.png', 'images/RandWalk46.png', 'images/RandWalk47.png', 'images/RandWalk48.png', 'images/RandWalk49.png', 'images/RandWalk50.png', 'images/RandWalk51.png', 'images/RandWalk52.png', 'images/RandWalk53.png', 'images/RandWalk54.png', 'images/RandWalk55.png', 'images/RandWalk56.png', 'images/RandWalk57.png', 'images/RandWalk58.png', 'images/RandWalk59.png', 'images/RandWalk60.png', 'images/RandWalk61.png', 'images/RandWalk62.png', 'images/RandWalk63.png', 'images/RandWalk64.png', 'images/RandWalk65.png', 'images/RandWalk66.png', 'images/RandWalk67.png', 'images/RandWalk68.png', 'images/RandWalk69.png', 'images/RandWalk70.png', 'images/RandWalk71.png', 'images/RandWalk72.png', 'images/RandWalk73.png', 'images/RandWalk74.png', 'images/RandWalk75.png', 'images/RandWalk76.png', 'images/RandWalk77.png', 'images/RandWalk78.png', 'images/RandWalk79.png', 'images/RandWalk80.png', 'images/RandWalk81.png', 'images/RandWalk82.png', 'images/RandWalk83.png', 'images/RandWalk84.png', 'images/RandWalk85.png', 'images/RandWalk86.png', 'images/RandWalk87.png', 'images/RandWalk88.png', 'images/RandWalk89.png', 'images/RandWalk90.png', 'images/RandWalk91.png', 'images/RandWalk92.png', 'images/RandWalk93.png', 'images/RandWalk94.png', 'images/RandWalk95.png', 'images/RandWalk96.png', 'images/RandWalk97.png', 'images/RandWalk98.png', 'images/RandWalk99.png', 'images/RandWalk100.png', 'images/RandWalk101.png'],
	    'width': 480,
	    'delay': 150,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
	$('#RandWalk').scianimator('play');
    });
})(jQuery);
