Title
========================================================

This Markdown document demonstrates plotting using google maps. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(CMcCode)
library(data.table)

dir("../General Code/CMcCode/R")

source("../general code/CMcCode/R/UsefulFUnctions.R")
source("../D3/googleMaps.R")

```

```{r, echo=FALSE, results='asis', warning=FALSE}
lst <- list(stations = list(svg = c(position = "absolute", color = "red"),
                          svg = c(width = "60px", height = "60px", "padding-bottom" = "100px", 
                                  "padding-right" = "100px", font = "12px sans-serif"),
                          circle = c(fill = "red", stroke = "black", "stroke-width" = "1px", "-webkit-animation-name" = "redPulse", 
                                   "-webkit-animation-duration" = "2s", "-webkit-animation-iteration-count" = "infinite"), 
                          "circle:hover" = c(fill = "blue", cursor = "pointer")), 
            marker_text = c(fill = "black", visibility = "hidden"))

cat(cgm_init())
cat(cgm_styles(lst))
#objects <- list(data = list(London = list(-0.1198244, 51.5112139, "Capital of Great Britain"), WashingtonDC = list(-77.0364641, 38.9072309, "Capital of United States")))

# This currently isn't doing anything
funs <- list(expandNode = '() {d3.select(this).transition().duration(1000).attr("r", 7)}', 
             contractNode = '() {d3.select(this).transition().duration(100).attr("r", 4)}')

# Get data for plotting
dat1 <- data.table(lon = c(-0.1198244, -77.0364641), lat = c(51.5112139, 38.9072309), city = c("London", "WashingtonDC"), description = c("Capital of Great Britain", "Capital of United States"))
data(world.cities, package = "maps")
dat2 <- data.table(world.cities) # [, Scale: = (1:10)*2]

# Set some random values to be used for plotting characteristics
dat2$Scale  <- (1:5)*4
dat2$Stroke <- (1:5)*2
dat2$Stroke <- (1:10)

# Create objects (similar to ggplot syntax: using map instead of aes, using add_point instead of geom_point)
objects1 <- add_point(dat1, map(lon = lon, lat = lat, fill = "blue", col = "seagreen", stroke = 2))
objects2 <- add_point(dat2[10100:10500],
                      map(lon = long, lat = lat, fill = pop, size = Scale, group = letters[Stroke], col = "red", alpha = .6),
                      opts = list(fill_log = T))
#objects2 <- add_point(dat2[10100:10110],map(lon = long,lat = lat,fill = "green"))

cat(cgm_js(objects2,jsFUNs = funs))


```


```{r,echo = FALSE,results = 'asis'}
cat("<div id='map_canvas' style=\"height: 600px;\"></div>")
```

Continue with other things in markdown file...

```{r,echo = FALSE}
plot(1:10)
```



