---
title: "Example Graphs"
output: html_document
---

```{r,echo=FALSE,warning=FALSE,comment=""}
library(networkD3)
library(rjson)
library(igraph)
# library(data.table)
# library(xtable)
# library(ggplot2)

setwd("/work/cmcneil/Miscellaneous/Personal/D3")
source("D3Force.R")

options(width=150)

vertices <- 20
edges    <- 15
randedges <- unique(matrix(ceiling(runif(edges*2)*vertices),ncol=2))
randedges <- randedges[randedges[,1]!=randedges[,2],]
ig <- graph(t(randedges),n=vertices,directed=F)

V(ig)$type     <- sample(1:3,length(V(ig)),replace=T)
V(ig)$group    <- V(ig)$type + (min(V(ig)$type)==0)
V(ig)$grpcol   <- ifelse(V(ig)$type==2,"slateblue","yellow")
V(ig)$grpnm    <- as.factor(c("Grp1","Grp2","Grp3")[V(ig)$group])
V(ig)$nodesize <- sample(1:16,length(V(ig)),replace=T)
V(ig)$index    <- V(ig)
V(ig)$Index    <- paste0("Vertex_",V(ig))
V(ig)$repel    <- -120*replace(rep(1,length(V(ig))),4:5,10)

sources <- NULL
for (i in 1:length(E(ig)))
  sources[i] <- as.numeric(V(ig)[inc(E(ig)[i])])[1]-1
targets <- NULL
for (i in 1:length(E(ig)))
  targets[i] <- as.numeric(V(ig)[inc(E(ig)[i])])[2]-1
E(ig)$source <- sources
E(ig)$target <- targets

#E(ig)$source <- sapply(1:length(E(ig)),function(i) as.numeric(V(ig)[inc(E(ig)[i])])[1]-1 )
#E(ig)$target <- sapply(1:length(E(ig)),function(i) as.numeric(V(ig)[inc(E(ig)[i])])[2]-1 )

E(ig)$value  <- sample(1:4,length(E(ig)),replace=T)
E(ig)$visitstowebsite <- sample(c(4,225,961),length(E(ig)),replace=T)
E(ig)$text   <- sample(c("Edge","Line","Link"),length(E(ig)),replace=T)


html1 <- myForce(ig)
# A lot of the graph characteristics can also be adjusted (HL indicates the value when it is highlighted).
html2 <- myForce(ig,
                   offset=30,
                   duration=1200,
                   nodes=list(charge=-200,
                              fill="seagreen",
                              fillHL="yellow",
                              strokewidth=3,
                              strokewidthHL=1),
                   links=list(length=180,
                              strokewidth=2,
                              strokewidthHL=3,
                              stroke="indianred",
                              strokeHL="black"),
                   nodedetails=list(items="type"),
                   linkdetails=list(items=c("value","text")),
                   nodetextbox=list(fill="white",
                                    stroke="navy",
                                    fillopacity=.9,
                                    strokeopacity=1,
                                    textitemcol="brown",
                                    textvaluecol="#F408ED"),
                   linktextbox=list(fill="lightgreen",
                                    stroke="green",
                                    fillopacity=.2,
                                    strokeopacity=.6))

# Graph object should also be able to be specified as a list containing two data.frames for vertex (nodes) and edge (links) attributes (NOT WORKING)
nodes.df <- as.data.frame(vertex.attributes(ig)) 
links.df <- as.data.frame(edge.attributes(ig))   # must include 'target' and 'source' fields referencing row numbers of nodes.df
graph <- list(v=nodes.df,e=links.df)

# Using formulas, the numerical graph characteristics and textbox output can also be functions of graph characteristics
html3 <- myForce(ig,
                   duration=100,
                   nodes=list(strokewidth = ~group-.5,
                              radius = ~sqrt(nodesize)*10,
                              stroke = "black",
                              strokeHL = "#AA0522",
                              fill = ~grpcol,
                              fillHL = ~grpcol,
                              radiusHL = ~sqrt(nodesize)*10,
                              charge = ~repel),
                   links=list(strokewidthHL = ~(value+3)/2,
                              length = ~value*40),
                   nodedetails=list(items = c("Renamed","Size minus group","Shifted index"),
                                    expr = list(~Index, ~nodesize-group, ~index+""+3)),
                   linkdetails=list(items = c("Incr group","Length"),
                                    expr = list(~value+5+"cm", ~value + " * constant value")))

# Recreate
html4 <- myForce(ig,
                   nodetextbox=list(strokeopacity=0,fillopacity=0),
                   nodedetails=list(items="",expr=list(~Index)),
                   mouseoverlink=F,offset=c(15,-7))
```

```{r,echo=FALSE,results='asis'}
forceNetwork(links.df,nodes.df,"source","target","value","index",Group="group",Nodesize="nodesize",opacity=1)
```

```{r,echo=FALSE,results='asis'}
d3init()
cat(html1)
cat(html2)
cat(html3)
cat(html4)
```
